### ISSUE TITLE
Obj to 3D Tiles pipeline

### ISSUE THREAD

**Issue by allyoucanmap** [geosolutions-it/digital-twin-toolbox#66]
We should introduce a pipeline to convert Obj files to 3D Tiles.

Requirements:

- Extend support of asset import for obj file included in a zip folder. The zip folder could include also material files and textures.
- Include a new backend task to support the conversion workflow (we could re-use the [mesh_tiling](https://github.com/geosolutions-it/digital-twin-toolbox/blob/mesh/backend/app/worker/photogrammetry/mesh_tiling.py) script to process the obj)
- Include a new frontend page to support this type of file:
  - preview will not be available in this phase
  - input available should be:
    - texture_image_size
    - tile_faces_target
    - depth
    - max_geometric_error
    - latitude
    - longitude
    - altitude
  - we should include also a small map to allow users to select the position from there instead to manually fill latitude, longitude and altitude inputs

**Comment by jo-chemla** [comment]
Hi there, in case it's useful, here are some examples of tools and that let you produce OGC 3D-tiles tileset out of mesh inputs: 
 - [fanvanzh/3dtiles](https://github.com/fanvanzh/3dtiles)
 - [kitware vtk 3d-tiles-generation](https://www.kitware.com/3d-tiles-generation-using-vtk/)
 - [py3dtiles](https://py3dtiles.org/) aims to support mesh tiling, but does not yet

**Comment by allyoucanmap** [comment]
Hi @jo-chemla thanks for sharing these links, we took a look at those libraries but for the moment we will re-use what we implemented for another experimental pipeline based on blender python API, anyway we will take into account these suggestions for future works

**Comment by jo-chemla** [comment]
Thanks for getting back, hopefully you can handle massive meshes at some point!
obj being ascii would probably not be the right mesh container format for 100M or even 1-10B triangles meshes, but usdc, fbx, or even older binary ply could be good. 

It's still not obvious to me at the moment which mesh 3D-tiler will become the de-facto open-source reference implementation. Probably [zeux/meshoptimizer](https://github.com/zeux/meshoptimizer) will be part of the solution - their work on meshlets CLOD probably can be an inspiration for simpler, HLOD structures building in a fast and memory-efficient pipeline!
